#https://docs.insomnia.rest/insomnia/environment-variables
spring:
  profiles:
    default: development
    #default: production
#Por padrao o spring boot usa o HikariCP como pool de conexoes (Bem robusto)