#https://docs.insomnia.rest/insomnia/environment-variables
spring:
  profiles:
    default: development
    #default: production

#Configuracoa Banner do Spring
banner:
  location: classpath:banner.txt
  charset: UTF-8

#Por padrao o spring boot usa o HikariCP como pool de conexoes (Bem robusto)