spring:
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
  application:
    name: myapp
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driverClassName: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      idle-timeout: 30000
      pool-name: VendasHikariCP
  jpa:
    open-in-view: false #https://vladmihalcea.com/the-open-session-in-view-anti-pattern/
                        #Permite que o hibernate mantenha a sessao aberta ate o final da requisicao se 'true'
                        #Para evitar o erro de lazy loading(LazyInitializationException),
                        #Mas pode causar problemas de performance e Relacoes OneToMany e ManyToMany com Fetch LAZY
    show-sql: true
    properties:
      hibernate:
        format_sql: true #https://www.baeldung.com/sql-logging-spring-boot
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update #create-drop - cria e destroi o banco a cada inicializacao
      #vamos deixar 'none' pois vamos criar o schema e dados via scripts la em baixo
    defer-datasource-initialization: true #retarda a inicializacao do datasource
  sql:
    init:
      mode: always #always, never, embedded - somente para h2 usa aways
      platform: postgresql
      #schema-locations: classpath:/schema_renomeado_para_nao_executar.sql #schema_renomeado_para_nao_executar.sql e data_renomeado_para_nao_executar.sql sao executados sempre que o spring boot inicia
      #data-locations: classpath:/data_renomeado_para_nao_executar.sql #schema_renomeado_para_nao_executar.sql e data_renomeado_para_nao_executar.sql sao executados sempre que o spring boot inicia
server:
  servlet:
    context-path: /base
  port: 8080
#https://medium.com/@patelsajal2/learn-how-to-enable-logging-of-sql-statements-in-spring-boot-with-this-comprehensive-tutorial-48c06bc080ab
logging:
  level:
    root: INFO
    org.springframework.jdbc.core.JdbcTemplate: INFO
    org.springframework.jdbc.core.jdbc: INFO
    org.springframework.web: INFO
    org.hibernate: INFO
    org.hibernate.type: INFO
    org.hibernate.stat: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO
    org.hibernate.type.descriptor.sql.BasicExtractor: INFO

#Configuracao TTL do cache no Redis classificado por CacheName
myapp:
  cache:
    redis:
      ttl: 15