spring:
  application:
    name: exemplo-aop-annotations-junit5
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:db
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    open-in-view: false
logging:
  level:
    root: INFO
    org:
    springframework:
    web: INFO
    aop: INFO
