spring:
  application:
    name: demo-specification-custom
  datasource:
    url: jdbc:h2:mem:demo;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;MODE=LEGACY;TRACE_LEVEL_FILE=4;
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  data:
    jdbc:
      dialect: h2
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
logging:
  level:
    root: info
    org.springframework: info
    sql: debug
